### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by calloatti** [Nuclearfarts/connected-block-textures#10]
connected-block-textures-0.1.1+1.16.jar

https://paste.ee/p/WTtH0

Reverting to connected-block-textures-0.1.0+1.16.jar fixes the crash

**Comment by TwilightFlower** [comment]
`connected_block_textures.mixins.json:IdentifierMixin target net.minecraft.class_2960 was loaded too early.`

This isn't my fault, someone's loading `Identifier` before mixin is initialized. Probably in preinit. This is bad.

**Comment by calloatti** [comment]
Well, the mod causing it probably fixed it in an update because I tried again and now it works. thanks.
