### ISSUE TITLE
Support MC 1.16.4

### ISSUE THREAD

**Issue by redbrain** [Nuclearfarts/connected-block-textures#21]
I mostly file these as a courtesy; 1.16.4 is the last version of 1.16 and requires minimal changes to support.
Update at your convenience.

**Comment by Dolphin2Point1** [comment]
It seems the version you can compile using the source on this repository will work on 1.16.4. If you download the source from github and build it, you should get a version that is compatible with 1.16.3 and 1.16.4.

**Comment by TwilightFlower** [comment]
yeah, i've just got to... actually release it. been lazy.
