### ISSUE TITLE
glass does not CTM properly

### ISSUE THREAD

**Issue by OakBricks-old** [Nuclearfarts/connected-block-textures#22]
![image](https://user-images.githubusercontent.com/65257189/103046372-92a4bc00-454d-11eb-911d-609fb3d47788.png)

glass does not CTM properly the texture for the ends are the ones that are seen of glass is left/right of other glass.

NO MODS (Fresh fabric install)
Version: latest from source

**Comment by OakBricks-old** [comment]
Looks like it only bugs out if the glass is facing north (Z view)

**Comment by OakBricks-old** [comment]
More pics of the bug
![image](https://user-images.githubusercontent.com/65257189/103047051-e0babf00-454f-11eb-8bcb-4fbdb46a209f.png)
in an actual server
![image](https://user-images.githubusercontent.com/65257189/103047166-3db67500-4550-11eb-810c-9de7dc368dac.png)

**Comment by TwilightFlower** [comment]
Ugh, this issue... I know the cause, I just know that fixing it _properly_ will be painful. There's probably a band-aid fix I could do, though.

**Comment by magneticflux-** [comment]
Also affects log tops in Faithfulx32:
![image](https://user-images.githubusercontent.com/9124288/104820445-5554e680-57fa-11eb-9891-577807f00978.png)

**Comment by DragonEggBedrockBreaking** [comment]
Can reproduce, can confirm

**Comment by Genau6502** [comment]
Would you be able to do that band-aid fix?

**Comment by Heitzenberg** [comment]
Any progress on this?

**Comment by TwilightFlower** [comment]
Finally got around to working on this mod again, fixed, will release soon
