### ISSUE TITLE
Crash on latest api/loader

### ISSUE THREAD

**Issue by Zentheon** [Nuclearfarts/connected-block-textures#24]
[crash-2021-01-13_14.32.32-client.txt](https://github.com/Nuclearfarts/connected-block-textures/files/5811190/crash-2021-01-13_14.32.32-client.txt)

**Comment by M1ch431** [comment]
Can confirm.

**Comment by TwilightFlower** [comment]
Known and fixed a while ago, I just don't like dealing with CF so I haven't published a build.

**Comment by Zentheon** [comment]
that's fair. Thanks for the update

**Comment by campbebj** [comment]
Could you recompile for github atleast?
