### ISSUE TITLE
Something's wrong with high resolution texture packs

### ISSUE THREAD

**Issue by Kira-NT** [Nuclearfarts/connected-block-textures#26]
## Description

The game freezes at the loading screen while trying to load a "heavy" resource pack. Also memory begins to leak during this process (perhaps after a while we'll get `OutOfMemoryException`, but I didn't wait for it to happen)

## Mod list

 - Fabric API
 - CBT

## Resource packs

- [Faithful-32x](https://www.curseforge.com/minecraft/texture-packs/faithful-32x) - Works fine since it provides x32 textures and its size is only 6-7 MB
- [NAPP_2.0](https://www.napplab.com/downloads/) - And this big boi (385 MB, x512) causes us some problems

**Comment by TwilightFlower** [comment]
Please post a crash log via a paste site or gist.

**Comment by Kira-NT** [comment]
@Nuclearfarts, there's no crash (and crash log by the obvious reasons) and technically game is alive and everything's fine except never-ending loading screen :)

`OutOfMemoryException` is my assumption, I never got a chance to check it, cause memory leaks at ≈5 MB/s on my machine ¯\\_(ツ)_/¯

**Comment by EvilSquirrelGuy** [comment]
I have this same issue, happening with Faithful x32.

Also has the never ending loading screen.
https://gist.github.com/EvilSquirrelGuy/6102207fb5512e2a5dcb619546d8c878
