### ISSUE TITLE
Stained glass glitchy on chunk borders

### ISSUE THREAD

**Issue by bvngee** [Nuclearfarts/connected-block-textures#28]
In this exact spot (on a chunk border) glass renders glitchy and allows color to leek through.
I could only recreate this in one certain spot, so I can't be sure exactly what the issue is. 

I am using Sodium, Indium, and CTM, along with a bunch of other mods, but the issue did persist when just using those three.

![2021-02-24_14 22 21](https://user-images.githubusercontent.com/69218859/109074630-dda59180-76ac-11eb-90a9-e6ff6ecc8e4e.png)
In this image I believe the black showing through the glass is the black concrete that is way below the glass.
(The floor is a bunch of layers of glass which is what's creating the reflection, not any shaders)

Another question (a separate problem afaik but didn't think it was worth it to make another issue) is that I am getting red lines in between glass blocks. Not sure what's causing that, maybe just a sodium bug?

**Comment by TwilightFlower** [comment]
This is a known issue with sodium's compact vertex format and will happen regardless of CBT being installed. Or it's just sodium not having transparency sorting.
