### ISSUE TITLE
Use stb_image instead of AWT/ImageIO

### ISSUE THREAD

**Issue by Leo40Git** [Nuclearfarts/connected-block-textures#3]
AWT is known to be finicky on Mac and Linux. You should probably move to stb_image. Look at Minecraft's resource pack loading code for examples.

**Comment by TwilightFlower** [comment]
None of the bad AWT stuff is loaded from using BufferedImage as far as I know, it _should_ be fine. If this is an actual issue, please let me know, otherwise I'll close this in a few days.

**Comment by Leo40Git** [comment]
Just thought I'd mention it. If it hasn't caused any issues yet, I suppose it's fine.

**Comment by Johni0702** [comment]
Just FYI, merely referencing BufferedImage can break things if that reference causes the class to be loaded at the wrong moment (presumably before MC sets up GLFW), I  have run into this with a mod of mine:
https://github.com/ReplayMod/jGui/blob/037d54f83a736123a7b834f2485b0adc08744033/src/main/java/de/johni0702/minecraft/gui/versions/Image.java#L22-L24

**Comment by NeRdTheNed** [comment]
https://discordapp.com/channels/507304429255393322/507982463449169932/741110063187623946 Here is an even more specific instance where this causes issues, specifically a segfault under incredibly specific circumstances. Probably a good idea to re-open.

**Comment by TwilightFlower** [comment]
#12 has significantly better initial report, closing this in favor of that issue.
