### ISSUE TITLE
Glass Panes connect incorrectly depending on the side they are viewed from

### ISSUE THREAD

**Issue by edwloef** [Nuclearfarts/connected-block-textures#34]
https://user-images.githubusercontent.com/75493688/112983103-8b4d0a00-915d-11eb-96d3-344a162ee89a.mp4

**Comment by DragonEggBedrockBreaking** [comment]
Possibly a duplicate of #30 ? https://github.com/Nuclearfarts/connected-block-textures/issues/30#issuecomment-789401736

**Comment by edwloef** [comment]
Oh yeah, probably
