### ISSUE TITLE
Incompatibility with Lithos pack

### ISSUE THREAD

**Issue by zml2008** [Nuclearfarts/connected-block-textures#4]
The Lithos pack (https://www.curseforge.com/minecraft/texture-packs/lithos-core-32x-1-6-1-11-complete) has CTM support, and appears to work under Optifine. However, some of the paths it uses are not valid `Identifier`s, which Optifine seems to accept just fine. The pack also uses some paths starting with `~` in its `matchTiles` specification -- which I don't see in the spec but which optifine seems to support.

[Log](https://paste.gg/p/anonymous/fc115c8f458e40a8a86c50c51bbca1c7) -- there's a combination of things CBT doesn't support yet (which is fine), and issues with naming that don't appear in optifine

When loading the pack with CBT installed, pack loading will fail if there are folders with invalid names (in this case just the `coal pillars` folder, and will dump exceptions from trying to load other textures (log from above is with the coal pillars name changed to be valid).

I don't know how common these things are in other packs -- but I wouldn't be surprised if these sorts of things pop up in other places too, since it sounded like at least for this pack CTM support was done a long time ago and then left fairly untouched. Are you able to work around the naming issues?

**Comment by TwilightFlower** [comment]
what the FUCK optifine. I literally CANNOT load those textures. EVERY resource query goes through an Identifier.

Wonder what fucking cursed mixin this will take.

**Comment by TwilightFlower** [comment]
Should be fixed in 0.1.1
