### ISSUE TITLE
1.17 support?

### ISSUE THREAD

**Issue by MenacingPerson** [Nuclearfarts/connected-block-textures#42]
I'd love to have cbt for 1.17, any ETA on when you're updating it?

**Comment by TwilightFlower** [comment]
When quilt becomes a thing I can develop a mod on.

**Comment by NebelNidas** [comment]
Quilt will be backwards compatible with Fabric, and its initial release won't be that different from Fabric anyways. So what's holding you back from doing it now?

**Comment by TwilightFlower** [comment]
The mod running on Fabric is a negative to me since the people in charge were personally dicks to me.

**Comment by NebelNidas** [comment]
Not having the mod updated will hurt the innocent users more than the actual fabric moderators 🤔

**Comment by TwilightFlower** [comment]
And I am not doing anything that would draw people to Fabric. No amount of arguing will convince me otherwise.

**Comment by NebelNidas** [comment]
Well, if you think that some Discord drama is more important than actually having usable mods, then that's on you 🤷‍♂️

**Comment by MenacingPerson** [comment]
late but wanna add, what would it draw people away from?

**Comment by TwilightFlower** [comment]
Wouldn't draw people away from anything, just draw people to Fabric, which I don't want.
