### ISSUE TITLE
Broken biome-dependant texture colour variations

### ISSUE THREAD

**Issue by RephlexZero** [Nuclearfarts/connected-block-textures#43]
Running under MultiMC with Manjaro, using the 1.17 compiled .jar, I did some testing to pin down what mod was causing the issue, connected block textures alone being enabled caused this to happen to the Stay True resource pack's birch leaves. They are the only instance I have seen of this happening though. Purely a visual error. No wisdom to provide but just wanted to report.

![image](https://user-images.githubusercontent.com/67481201/124310287-e2e78100-db63-11eb-8ad3-85c16a6fd151.png)

**Comment by TwilightFlower** [comment]
oh god what the fuck

full mod list?

**Comment by RephlexZero** [comment]
> oh god what the fuck
> 
> full mod list?

This visual bug is present with:
Fabric API 0.36.0+1.17
Iris(Sodium) 1.1.0+rev.f06a69d
Indium 1.0.0+rev.820073e
Connected Block Textures 0.1.5+1.17

I had more mods, but just running with only these enabled was enough. This is probably a compatibility issue with the new Iris engine.

**Comment by TwilightFlower** [comment]
1. That is not my mod, report to the fork.
2. This is likely Sodium, Indium, or Iris's fault. Don't report bugs you can't reproduce without those mods.
