### ISSUE TITLE
1.17 support?

### ISSUE THREAD

**Issue by Soham52** [Nuclearfarts/connected-block-textures#45]

**Comment by Un1q32** [comment]
im wondering the same thing.  i cant use optifabric because the current optifine preview crashes when loaded with optifabric or forge

**Comment by Soham52** [comment]
> im wondering the same thing.  i cant use optifabric because the current optifine preview crashes when loaded with optifabric or forge

You may use ctm fabric 
https://www.curseforge.com/minecraft/mc-mods/ctm-fabric

**Comment by KyGost** [comment]
> > im wondering the same thing.  i cant use optifabric because the current optifine preview crashes when loaded with optifabric or forge
> 
> You may use ctm fabric
> https://www.curseforge.com/minecraft/mc-mods/ctm-fabric

This requires unique texture packs though, does it not?
(Or at least not the majority norm that is the optifine format)

**Comment by Soham52** [comment]
Yes it does, but it's not that complex

**Comment by KyGost** [comment]
> Yes it does, but it's not that complex

Nonetheless the typical end user isn't going to have the know-how nor the effort to convert a pack. Unless there is an automated tool?
