### ISSUE TITLE
CBT not sensing fabric mod

### ISSUE THREAD

**Issue by hatan24** [Nuclearfarts/connected-block-textures#7]
I downloaded Fabric, sodium and then CBT on my macbook air running bootcamp windows. I got Sodium to work, but when I added CBT, it crashed and said:  - Mod connected_block_textures depends on mod {fabric @ [*]}, which is missing! Even though I downloaded it on fabric. It still crashes without sodium, and I don't know how I can get it to work. I'm not very good with this stuff; sorry if it's because of something stupid.

**Comment by 5HT2** [comment]
You need to install the fabric api mod. Fabric is designed around the UNIX philosophy and as such if some mod depends on another mod, you need to install the dependencies as well. As such, download [this](https://www.curseforge.com/minecraft/mc-mods/fabric-api) for the correct version and put it in your mods folder, this isn't CBT's fault

**Comment by TwilightFlower** [comment]
Yep, install fabric API. Also, incompatible with Sodium as of now -- see https://github.com/jellysquid3/sodium-fabric/issues/61
