### ISSUE TITLE
CBT Refuses to transform non-vanilla models

### ISSUE THREAD

**Issue by grondag** [Nuclearfarts/connected-block-textures#9]
Here: https://github.com/Nuclearfarts/connected-block-textures/blob/fa21be37fe13afb2bd20fb92631520e879b08b8c/src/main/java/io/github/nuclearfarts/cbt/model/CBTBakedModel.java#L28

This prevents JMX/Canvas from loading vanilla models as meshes to improve performance and memory utilization.

Is this restriction necessary, given that CBT calls `emitBlockQuads` anyway?

For now, Canvas checks if CBT is loaded and falls back to vanilla models if so.

**Comment by TwilightFlower** [comment]
Ah, that's a holdover from when I emitted the quads differently. I should
be able to remove that check and have it Just Work.

**Comment by grondag** [comment]
Great.   Lemme know when you've made the change so I can remove my hack.

Thanks!

**Comment by TwilightFlower** [comment]
Should be fixed!
